name: SilenceMobs
main: com.github.joelgodofwar.sm.SilenceMobs
version: 1.10_1.0.7
author: JoelYahwehOfWar
api-version: 1.13

commands:
  sm:
    description: Shows SilenceMobs help.
    usage: /<command>
  silencemobs:
    description: Shows SilenceMobs help.
    usage: /<command>

permissions:
  silencemobs.use:
    description: Allows player to silence mobs.
    default: true
  silencemobs.reload:
    description: Allows the player to use "/sm reload" command.
    default: op
  silencemobs.toggledebug:
    description: Allows the player to use "/sm toggledebug" command.
    default: op
  silencemobs.showUpdateAvailable:
    description: Shows player that there is a version update.
    default: op
