# change to false to stop auto-update-check
auto_update_check: true

# set to true before sending a log about an issue.
#logs trace data required to pinpoint where errors are.
debug: false

# 中文 (zh_CN), 中文 (zh_TW), čeština (cs-CZ), Deutsche (de_DE), English (en_US), Español (es_MX),
# Français (fr_FR), Nederlands (nl_NL), Portuguese (pt_BR)
lang: en_US